version: "3"
services:
  nginx:
    restart: always
    build: 
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "4030:80"
    volumes:
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/nginx/html:/usr/share/nginx/html"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/nginx/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/nginx/nginx/lognginx:/var/log/nginx"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/java:/java"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/cloud_drive:/cloud_drive"
    command: /bin/bash -c /java/wrapper.sh
    links:
      - mysql57

  mysql57:
    restart: always
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/mysql/mysql:/var/lib/mysql"
      - "/E/Gdansk University of Technology/fifth_semester/InternetiServicesArchitectures/Lab/Lab6/docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
